#!/usr/bin/env node

// hook up commander for the help chain
require('commander').parse(process.argv);

var https = require('https');
var querystring = require('querystring');

var config = require('./config/api.json').servers;
var appId = require('./config/app.json').application_id;

var body = querystring.stringify({
  application_id: appId,
  game: 'wotb'
});

var options = config.info;

options.hostname = config.hostname;
options.headers = {
  'Content-Type': 'x-www-form-urlencoded',
  'Content-Length': body.length
};

var request = https.request(options, function createRequestCb(response) {
  var data = [];

  if (!('x-api-version' in response.headers)) {
    console.error('ERROR: No API version found in response headers');
  } else if (response.headers['x-api-version'].substr(0, 2) !== '2.') {
    console.warn('WARNING: May break because the API version does not match');
  }

  response.setEncoding('utf8');
  response.on('data', Array.prototype.push.bind(data));
  response.on('end', function responseEndedCb() {
    console.dir(JSON.parse(data.join('')).data.wotb, {colors: true});
  });
});

request.on('error', function requestErrorCb(err) {
  console.error(err.stack);
});

request.write(body);
request.end();
