#!/usr/bin/env node

var request = require('./lib/request.js')('servers');

module.exports = {
  info: info
};

if (require.main === module) {
  // hook up commander for the help chain
  require('commander').parse(process.argv);

  main();
}

function main() {
  info(_dir);
}

function _dir(err, data) {
  if (err) throw err;
  console.dir(data, {colors: process.stdout.isTTY});
}

function info(callback) {
  request('info', {
    game: 'wotb'
  }, function infoRequestCb(err, data) {
    if (err) return callback(err);
    callback(null, data.wotb);
  });
}
