#!/usr/bin/env node

// hook up commander for the help chain
require('commander').parse(process.argv);

var request = require('./lib/request.js')('servers');

module.exports = {
  info: info
};

if (require.main === module) {
  main();
}

function main() {
  info(_dir);
}

function _dir(err, data) {
  if (err) return console.error(err.stack);
  console.dir(data, {colors: true});
}

function info(callback) {
  request('info', {
    game: 'wotb'
  }, function infoRequestCb(err, data) {
    if (err) return callback(err);
    callback(null, data.data.wotb);
  });
}
